apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
        - image: gcr.io/xend-326306/comment-management:latest
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - name: liveness-port
              containerPort: 5010
              protocol: TCP
          # env
          env:
            - name: DB_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection-ip
                  key: db_host
